### ISSUE TITLE
issue with "$" before rule name

### ISSUE THREAD

**Issue by kaspar030** [michaelforney/samurai#16]
samurai fails to parse this:

```
cflags = -Wall

rule cc
  command = gcc $cflags -c $in -o $out

build foo.o: $
        cc foo.c
```

with the following error: ```samu: build.ninja:6:14: expected name```. (it doesn't expect the ```$\n``` that wraps the line).

ninja parses it just fine. I stumbled over this bug as the python ninja file generator code that comes with ninja creates lines like that if they'd be too long without the "$".

**Comment by michaelforney** [comment]
Thanks for the bug report. It's good to test samurai against a variety of generators to hit any corner cases like these.

It looks like we are only handling escaped newlines in strings or path lists. This handles most cases, but not newlines between rule names, keywords, etc. I pushed a commit, which I think should address the issue.
