### ISSUE TITLE
"samu -t clean" does not clean depfiles

### ISSUE THREAD

**Issue by bonzini** [michaelforney/samurai#17]
If a depfile is present in the build directory, "ninja -t clean" will remove it. Samurai does not have the same behavior.

**Comment by michaelforney** [comment]
Thanks for the report. It looks like rsp files also needs to be cleaned. I pushed a fix for this, but I think there is still some room for improvement:
- When expanding `$depfile` and `$rspfile` for removal, we should be using the un-shell-escaped `$in` and `$out`. This also needs to be fixed when initially writing `$rspfile` in build.c:jobstart. I'll open a separate issue for this.
- When cleaning a target (with `ninja -t clean $target`), ninja also removes `$depfile` and `$rspfile` for the edge that generates the target and any (direct or indirect) dependencies of the target (though it doesn't remove any other outputs generated by those edges).
- ninja has some special handling to avoid visiting a dependency of an explicitly specified target more than once, and also to avoid attempting to remove a path more than once. We could possibly do the same.
