### ISSUE TITLE
WARNING: Could not create compilation database.

### ISSUE THREAD

**Issue by orbea** [michaelforney/samurai#19]
OS: `Slackware64-current`
samu: `0.6`
meson: `0.50.1`

I found when I configure a build with meson while `samu` is installed and `ninja` is not installed it will print this warning.
```
Found ninja-1.9.0 at /usr/bin/samu
samu: unknown tool 'compdb'
WARNING: Could not create compilation database.
```
If `ninja` is installed this warning vanishes and I have not noticed any other issues when this warning is present. It seems to happen regardless of what project I try to build.

What does this warning mean? Is there a way to silence it?

I have found this project, but building and installing it with either python2 or python3 does not seem to help.

https://github.com/Sarcasm/compdb

**Comment by michaelforney** [comment]
The warning is safe to ignore. meson tries to create a `compile_commands.json` database using `ninja -t compdb` during configure, and samurai doesn't support that subtool. However, as far as I know, this file is only used to provide some integration with certain IDEs.

I don't think there is a way to disable the warning (relevant code is https://github.com/mesonbuild/meson/blob/03d34a79f8632bd8d84d06e1f76b2fdba00a9be0/mesonbuild/backend/ninjabackend.py#L311-L323), but I agree it is a little annoying. Maybe it's worth talking with the meson developers about silently ignoring failed attempts to create `compile_commands.json`? After all, it doesn't affect the build in any way.

**Comment by michaelforney** [comment]
In fact, I think the only two reasons why meson needs to detect the ninja/samu command is to generate that compdb and to create a phony `ninja clean` target that internally calls `ninja -t clean`. Not sure why... I guess some people are used to `make clean`?

I tried to argue that meson shouldn't have to know the ninja command, but wasn't too successful: https://github.com/mesonbuild/meson/issues/3405

**Comment by orbea** [comment]
Thanks for the details explanation, meson should probably at least not do that if it finds samu. I'll bring this up with them later.
