### ISSUE TITLE
Error log "bad depfile: multiple outputs:" is missing the first char of the first string when logging

### ISSUE THREAD

**Issue by rehaby** [michaelforney/samurai#24]
The following log:
samu: bad depfile: multiple outputs: ibraries/stdafx.h != LicenseThread.o

Should be:
samu: bad depfile: multiple outputs: Libraries/stdafx.h != LicenseThread.o

This is on version 0.7

**Comment by michaelforney** [comment]
Thanks for the report. Could you post the contents of the .d file for LicenseThread.o? You can run `ninja -d  keepdepfile` so it doesn't get removed (I should probably support this option in samurai). That would help me figure out what's going wrong in the parser.

**Comment by rehaby** [comment]
I've had to remove most of the contents of the file as its from work, but I've added comment to say how many lines and in what format. If you need more I can try getting a .d file from one of the open source libraries we use
[LicenseThread.o.d.txt](https://github.com/michaelforney/samurai/files/3817578/LicenseThread.o.d.txt)

**Comment by michaelforney** [comment]
This should be fixed now. I've also implemented `-d keeprsp` and `-d keepdepfile` to make debugging easier.

Thanks again for using samurai and reporting this issue :)
