### ISSUE TITLE
ninja: unknown tool 'compdb'

### ISSUE THREAD

**Issue by perfect7gentleman** [michaelforney/samurai#25]
I've been using samurai as replacement for ninja in Gentoo.
Version - 0.7
```
Found ninja-1.9.0 at /usr/bin/ninja
ninja: unknown tool 'compdb'
WARNING: Could not create compilation database.
```

**Comment by michaelforney** [comment]
Do you want to use the `compile_commands.json` created by `ninja -t compdb`, or are you just concerned about the warning?

If you don't need `compile_commands.json`, you can safely ignore the warning (and maybe ask meson people to stop printing it).

Personally, I have no use for it, so I won't be implementing `-t compdb`, but I would probably accept a pull request if someone else did.

**Comment by perfect7gentleman** [comment]
I just concerned about the warning and its futher compability as ninja replacement. I want to fill feature request to use samurai on ninja in Gentoo build systems.
