### ISSUE TITLE
Support for samu -t targets

### ISSUE THREAD

**Issue by Bl4ckb0ne** [michaelforney/samurai#39]
When using `meson` on a big project, I often like to know the available targets, but the feature seems to not be present in `samurai`.

It's not required by any build and not blocking my work, so the priority is pretty low.

[ninja implementation][1]

[1]: https://github.com/ninja-build/ninja/blob/d986e4db5630cf1c5547e69b5556f006f7d3444a/src/ninja.cc#L418

**Comment by michaelforney** [comment]
I agree that this seems like a useful subtool.

Do you think you might be able to try implementing it yourself? I think it should be fairly straightforward.

**Comment by Bl4ckb0ne** [comment]
Why not, that could be a fun task. Is there already a list of the available targets stored somewhere in the code?

**Comment by michaelforney** [comment]
Awesome! There is a linked list of edges in `graph.h:alledges`. You can enumerate through all the targets by going through the output nodes of each edge.

To add a new subtool, you just need to write a function for it, then add an entry to the tools array in tool.c

**Comment by Bl4ckb0ne** [comment]
Souds good, I'll dig into that when I can find a little bit of time. Is there an IRC channel where I can reach you if I have small questions?

**Comment by michaelforney** [comment]
Feel free to PM me. My nick is mforney on freenode.

**Comment by Bl4ckb0ne** [comment]
Will do, thanks!
