### ISSUE TITLE
Implement `-l` option (job scheduling based on load average)

### ISSUE THREAD

**Issue by orbea** [michaelforney/samurai#41]
Is there any reason samu does not support the `-l` argument as ninja does?

From `ninja --help`.
> -l N     do not start new jobs if the load average is greater than N

**Comment by michaelforney** [comment]
No reason other than I didn't implement it.

It would have to be guarded by an ifdef since getloadavg is non-POSIX.

**Comment by orbea** [comment]
Thanks for the reply, I did not realize that about getloadavg. I'm fine with whatever you decide is best here, but I was curious as I was told this is part of the gentoo eclass for ninja and then noticed that samurai does not support it.

**Comment by orbea** [comment]
@michaelforney Maybe it might be nice for at least the short term it would be implemented as a no-op and prints a short warning about not being implemented instead of outright failing? This might help with compatiblity and ninja.

**Comment by Salamandar** [comment]
I'm wondering if I'd have some time to implement it. The answer is probably yes. That wouldn't be very difficult.

**Comment by Salamandar** [comment]
I'm working in #50.
