### ISSUE TITLE
Alpine Linux - build of chromium unknown target '-w'

### ISSUE THREAD

**Issue by TBK** [michaelforney/samurai#43]
Alpine has replaced ninja with samu (1.0 with these [patches](https://git.alpinelinux.org/aports/tree/main/samurai?h=master)). Symlink /usr/bin/ninja -> samu

I am trying to build Chromium and unfortunately samu errors out on:
```sh
>>> chromium: Bootstrapping GN
ninja: unknown target '-w'
Traceback (most recent call last):
  File "tools/gn/bootstrap/bootstrap.py", line 137, in <module>
    sys.exit(main(sys.argv[1:]))
  File "tools/gn/bootstrap/bootstrap.py", line 123, in main
    ['ninja', '-C', gn_build_dir, 'gn', '-w', 'dupbuild=err'])
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ninja', '-C', '/home/builder/aports/community/chromium/src/chromium-80.0.3987.122/out/Release/gn_build', 'gn', '-w', 'dupbuild=err']' returned non-zero exit status 1
```
Related code: https://github.com/chromium/chromium/blob/80.0.3987.122/tools/gn/bootstrap/bootstrap.py#L123

**Comment by michaelforney** [comment]
You'll need sync chromium past this commit (or cherry-pick it):
https://chromium.googlesource.com/chromium/src/+/53b414cba10bc3c38fca88c330d2146722b4e54c%5E%21/

samurai follows the POSIX Utility Syntax Guidelines, so does not allow operands intermixed with options. I'll add this to the README.

**Comment by TBK** [comment]
Thanks for the quick reply and solution :+1:

**Comment by michaelforney** [comment]
See also:
https://lists.alpinelinux.org/~alpine/devel/%3CBYZDB5LH4OVY.9FDVF5I3J954%40homura%3E#%3CCAGw6cBsAdr=hfyk_vKrUyuBhkmWBf9RB=CT0+T08v76Pif5RAg@mail.gmail.com%3E
https://github.com/michaelforney/aports/commit/25673672b5f076ac5cca0409d42c5137e1e8d53b
