### ISSUE TITLE
lapack-1.9.0 requires ninja version 1.10

### ISSUE THREAD

**Issue by orbea** [michaelforney/samurai#75]
OS: `gentoo`
samurai: `1.2`
lapack: `1.9.0`
cmake: `3.20.2`

When building lapack the build fails:
```
CMake Error at CMakeLists.txt:3 (project):
  The Ninja generator does not support Fortran using Ninja version

    1.9

  due to lack of required features.  Ninja 1.10 or higher is required.
```

The lapack source is here: https://github.com/Reference-LAPACK/lapack

**Comment by michaelforney** [comment]
CMake Fortran support requires on dyndeps, which is the main feature in 1.10. Closing in favor of #36.

**Comment by orbea** [comment]
Thanks, I didn't notice that this was a duplicate of the other issue.
