### ISSUE TITLE
Unreasonably large maxjobs leads to segfault

### ISSUE THREAD

**Issue by neuschaefer** [michaelforney/samurai#8]
```
$ ./samu -j1000000
Segmentation fault (core dumped)
```
(Tested on Debian Linux with glibc)

This is because of the `jobs` and `fds` arrays in `build()`.

Perhaps `maxjobs` should be clamped to a reasonable maximum.

**Comment by michaelforney** [comment]
I fixed this for now by allocating these arrays on the heap. This weekend, I will look into allocating jobs as they are required to avoid unnecessarily large allocations in this case.
