### ISSUE TITLE
Windows: msys2 + mingw-w64: warning

### ISSUE THREAD

**Issue by vtorri** [michaelforney/samurai#85]
I don't know if you want a warning free compilation, but here it is:

c99 -O1 -std=c99 -Wall -Wextra -Wpedantic -Wno-unused-parameter -c -o graph.o graph.c
In file included from graph.c:2:
graph.c: In function ‘nodepath’:
graph.c:122:30: warning: array subscript has type ‘char’ [-Wchar-subscripts]
  122 |                 if (!isalnum(*s) && !strchr("_+-./", *s))
      |                              ^~

just cast *s to int

**Comment by vtorri** [comment]
i can do a PR if you want

**Comment by michaelforney** [comment]
Yes, a PR would be appreciated. Thanks!

**Comment by vtorri** [comment]
@michaelforney see #88
