### ISSUE TITLE
allow Makefile to set PREFIX

### ISSUE THREAD

**Issue by vtorri** [michaelforney/samurai#90]
Hello

in Makefile, i propose to allow the user to set PREFIX when compiling:

PREFIX?=/use/local

@michaelforney do you agree ?

**Comment by nekopsykose** [comment]
?= is not allowed in posix make (see the .POSIX declaration)  

overriding the PREFIX already works, if you either do `make PREFIX= ..`, or pass `-e` (for environment vars) to make if using a gnu make or similar

**Comment by vtorri** [comment]
I tried in OpenIndiana and it failed I retry and It works. I guess there was a typo in my first make command

thank you

closing
