### ISSUE TITLE
Solaris: getloadavg() requires sys/loadavg.h

### ISSUE THREAD

**Issue by vtorri** [michaelforney/samurai#91]
See its [man page](https://docs.oracle.com/cd/E36784_01/html/E36874/getloadavg-3c.html)

so something like this in build.c

```
#ifdef __sun
#include <sys/loadavg.h>
#endif
```

**Comment by vtorri** [comment]
@michaelforney If you agree, I can make a PR for this

**Comment by capezotte** [comment]
This can be bundled with #87, which also updates the guards for macOS.

**Comment by vtorri** [comment]
@capezotte I don't know. Maybe @michaelforney has an opinion about this

**Comment by michaelforney** [comment]
I don't want to add a bunch of platform-specific ifdefs to samurai. Now it is disabled by default, which should fix the build issue on Solaris (and other platforms).

If you want to enable it, add `-D HAVE_GETLOADAVG` to your `CFLAGS` and patch `build.c` to include `sys/loadavg.h`.

**Comment by vtorri** [comment]
like compat.h or something like that

**Comment by michaelforney** [comment]
I'm not interested in meson. make works everywhere and is a POSIX standard tool. meson isn't and only supports a hardcoded set of compilers. I'm also not interested in ifdefs, even if they are contained in a single file.

It is simple enough for the packager to add `CFLAGS='-D HAVE_GETLOADAVG -include sys/loadavg.h'` to their make invocation.
